version: '3'
services:
  ds:
    build: .
    ports:
      - "8080:8888"
    volumes:
      - "$PWD/data:/app/data"
      - "$PWD/notebooks:/app/notebooks"
    environment:
      - JUPYTER_TOKEN=remoteds
